name: SuperTux
markdown: kramdown
highlighter: rouge
# baseurl: https://supertuxproject.org
exclude:
  - README.md
output: true

gems:
  - jekyll-feed

permalink: /news/:year/:month/:day/:title
timezone: UTC
